LEARNING_SETUP:
  BATCH_SIZE: 20 #How many images to include in batch when running inference, adjust according to GPU memory
  OUTPUT_PATH: '/home/feiyan/test_generate/'
  #save_path = '/home/feiyan/test_generate/'
  #save_path = '/home/feiyan/test_generate_rc2/'
  #save_path = '/home/feiyan/test_generate_rc4/'
  #save_path = '/home/feiyan/test_generate_samepad/'

DATASET_SETUP:  
  DHF1K_PATH: '/data/DHF1K/'
  UCF_PATH: NULL
  HOLLYWOOD_PATH: NULL
  
MODEL_SETUP:
  DECODER : ['d1', 'd2', 'd3']
  CHANNEL_REDUCTION: 1
  INPUT_SIZE: 16
  OUTPUT_SIZE: 1
  SINGLE: [True, True, True]
  FORCE_MULTI: False
  D1_LAST: False
  MODEL_WEIGHTS: '../../Sal_dist/pretrained/d1d2d3_S_lt.pth'
  #model_path = '../weights/d123s_rc2_rc1T.pth'
  #model_path = '../weights/d123s_rc4_rc1T.pth'